services:
  - type: web
    name: rakhi-2k25
    env: static
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main 